---
title: "Dragon_Phylogeny"
author: "Roshael Chellappah (20103016)"
date: "09/03/2022"
output: html_document
---

*GitHub*
Username: RoshaelC
Repository Link: https://github.com/RoshaelC/DNAalignment.git 

## Import Data
```{r}
library(ape)
DragonNexusDF <- read.nexus.data("input/DragonMatrix.nex")
head(DragonNexusDF)
names(DragonNexus)

DragonNexusDF <- data.frame(matrix(unlist(DragonNexus), ncol = 78, byrow = T))
row.names(DragonNexusDF) <- names(DragonNexus)
head(DragonNexusDF)

DragonDist <- dist(DragonNexusDF, method = "binary")
DragonDistMat <- as.matrix(DragonDist)
```

# Visualizing the Matrix
```{r}
library(reshape2)
PDat <- melt(DragonDistMat)
dim(DragonDistMat)
head(DragonDistMat)

dim(PDat)
head(PDat)
```
## Weights
Setting up the weight distribution as done in Dragon Phylogeny Tutorial
```{r}
WeightsDat <- read.csv("input/Weights.csv")

Weights <- paste0(WeightsDat$Weight, collapse = "")
Weights <- strsplit(Weights, split = "") [[1]]

WeightsNum <- rep(NA, length(Weights))

for (i in 1:length(WeightsNum)){
  if (Weights[i] %in% LETTERS){
    WeightsNum[i] <- which(LETTERS == Weights[i]) + 9
  } else {
    WeightsNum[i] <- Weights[i]
  }
}
WeightsNum <- as.numeric(WeightsNum)

length(WeightsNum)

WtDragonNexus = DragonNexus

for (i in 1:length(DragonNexus)){
  RepWeight <- DragonNexus[[i]] == 1
  WtDragonNexus[[i]][RepWeight] <- WeightsNum[RepWeight]
  RepWeight <- NA
}
```

Calculate the distance matrix
```{r}
WtDragonNexusDF <- data.frame(matrix(unlist(WtDragonNexus), ncol = 78, byrow = T))
row.names(WtDragonNexusDF) <- names(WtDragonNexus)
WtDragonDist <- dist(WtDragonNexusDF, method = 'euclidean')

WtDragonDistMat <- as.matrix(WtDragonDist)

WtPDat <- melt(WtDragonDistMat)
ggplot(data = WtPDat, aes(x = Var1, y = Var2, fill = value)) +
  geom_tile() + scale_fill_gradientn(colours = c("white", "blue", "green", "red")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

Plotting the Tree
```{r}
str(WtDragonTree)
```

Formatting the Tree
```{r}
head(WtDragonTree$tip.label)

Country <- gsub("[0-9\\.]+([^X]*).*", "\\1", WtDragonTree$tip.label)

Country

CountryGroups <- split(WtDragonTree$tip.label, Country)
CountryGroups

WtDTcol <- groupOTU(WtDragonTree, CountryGroups)
str(WtDTcol)

ggtree(WtDTcol, layout = "circular") + geom_tiplab(size = 2, aes(angle = angle)) + geom_highlight(node = 43, fill = "purple") + geom_highlight(node = 42, fill = "khaki3") + geom_highlight(node = 5, fill = "darkorange2") + xlim(-50, NA)
```
# Dragon Images
[Dragon 1]!(https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn.mos.cms.futurecdn.net%2FJYEXpJURGks76oHVBc5cik-1200-80.jpg&imgrefurl=https%3A%2F%2Fwww.livescience.com%2F25559-dragons.html&tbnid=5fxZrDx5JaqkgM&vet=12ahUKEwjE_KeD2rr2AhWto3IEHezjBQEQMygAegUIARDWAQ..i&docid=M3lf1aWtGsjSyM&w=1200&h=675&q=dragons&ved=2ahUKEwjE_KeD2rr2AhWto3IEHezjBQEQMygAegUIARDWAQ)

[Dragon 2]!(https://sp-ao.shortpixel.ai/client/q_glossy,ret_img,w_1050,h_485/https://thebrowngeeks.com/wp-content/uploads/2020/10/Dragon-Listicle-Feature-1050x485.jpg)

[Dragon 3]!(https://artsphere.org/wp-content/uploads/2018/04/purple-dragon-400x340.jpg)



